name: 'proyecto_atp'
version: '1.0.0'
config-version: 2

profile: 'default' # Asegúrate de que esto coincida con lo que pusiste al configurar la conexión

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  proyecto_atp:
    # Configuración global para el proyecto (opcional)
    +database: TFG  # En Databricks, 'database' en dbt equivale al Catálogo

    # Capa de Staging 
    # Los modelos que pongas en la carpeta 'models/staging' irán a TFG.silver
    staging:
      +materialized: view
      +schema: silver 

    # Capa de Marts
    # Los modelos que pongas en la carpeta 'models/marts' irán a TFG.gold
    marts:
      +materialized: table
      +schema: gold